version: '3.8'

services:

  mynodeservice:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      
  mongodb:
    image: mongo
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge